### ISSUE TITLE
review README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by PhilipMay** [telekom/HPOflow#31]
Review `README.md` and `CONTRIBUTING.md`

- is there something missing? maybe compare with optuna and transformers
- spelling
- idiomatic english
- consistency
- correctness
- links ok?
- ...

PS: The real documentation is still missing and a know issue.

**Comment by PhilipMay** [comment]
Maybe @twolffpiggott can do that?

**Comment by PhilipMay** [comment]
I think the headline "Code of conduct" should be "Code of Conduct" in CONTRIBUTING.md
Same for "Engaging in our project" -> "Engaging in our Project"

**Comment by twolffpiggott** [comment]
Sounds good 👍

**Comment by PhilipMay** [comment]
> Sounds good 👍

Hey @twolffpiggott - what does that mean?
Are you done with review and everything is ok or does it mean you will review later?
Sorry I am confused. :-)

**Comment by twolffpiggott** [comment]
No worries, I should be more explicit!

I mean that I will be doing the review as suggested. First priority for today is the transformers integration, then may be able to complete the review today as well; will update on this

**Comment by PhilipMay** [comment]
@michalharakal as discussed today:
Maybe you could also hava a look on those 2 documents.
Perhaps check if something should be added to the Style Guidelines  and so on.

**Comment by PhilipMay** [comment]
Changes go to #40

**Comment by michalharakal** [comment]
@PhilipMay what about versioning scheme for the library itself? like https://semver.org/ ?

**Comment by PhilipMay** [comment]
> @PhilipMay what about versioning scheme for the library itself? like https://semver.org/ ?

Good point Michal! Could you add that to the PR #40 which is opened by Tim?
Just push to this branch: https://github.com/telekom/HPOflow/tree/review-initial-documentation
Maybe at release checklist or styleguide - I am not sure.

**Comment by michalharakal** [comment]
@PhilipMay We could also have github action releasing to pypi bound to the setting of the version tag, so only if a new git tag is set, a an upload to pipy is started. I would this separate from PR #40 and create a new one for the release action.

**Comment by PhilipMay** [comment]
> @PhilipMay We could also have github action releasing to pypi bound to the setting of the version tag, so only if a new git tag is set, a an upload to pipy is started.

Yes. That would be possible. The reason why I wanted to have the version number in git is that it is possible to install the package with `pip install git+<gut_url>`. If you do that the version number also should be right. But we could do both...

Maybe we should open a new issue end describe what the action should do and when and how the version number is handled and where. An when exactly the version is updated to which value.

**Comment by PhilipMay** [comment]
The PR #40  from @twolffpiggott is merged now

@michalharakal I created 2 new issues for your ideas:
- #49 
- #50
