### ISSUE TITLE
Flake8 ignore list for Black compatibility

### ISSUE THREAD

**Issue by twolffpiggott** [telekom/HPOflow#38]
Flake8 raises a warning for "E203" when it encounters a Black decision to insert whitespace before `:` in slicing syntax.

[Black's behaviour is more correct here](https://github.com/psf/black/issues/315), so my suggestion is to add "E203" to the flake8 config ignore list.

i.e. in `setup.cfg`:

```
[flake8]
...
extend-ignore = E203

**Comment by PhilipMay** [comment]
I will change that. Thanks @twolffpiggott

**Comment by PhilipMay** [comment]
@twolffpiggott I see you change that in PR #39

**Comment by twolffpiggott** [comment]
> @twolffpiggott I see you change that in PR #39

Yes, I needed to bring it in in order to satisfy the formatting tests
