### ISSUE TITLE
add `transformers.py`

### ISSUE THREAD

**Issue by PhilipMay** [telekom/HPOflow#8]
@twolffpiggott should we add this here or to an other project we open source?

https://github.com/PhilipMay/mltb/blob/master/mltb/integration/transformers.py

**Comment by PhilipMay** [comment]
Please also add yourself (@twolffpiggott ) to the code owners section like I did: https://github.com/telekom/HPOflow/blob/main/CONTRIBUTING.md#code-owners

**Comment by twolffpiggott** [comment]
Will be doing opening the PR today :)
